/*
|--------------------------------------------------------------------------
| PRINCIPAL
|--------------------------------------------------------------------------
*/

document.body.addEventListener('keyup', (event) => { // Adiciona evento de soltar a tecla ao body (tela toda)...
    handlePlaySound(event.code.toLowerCase()); // Chama a função e passa o parâmetro do código da tecla transformando tudo em caixa baixa...
});

const button = document.querySelector('.drums__composer button');
button.addEventListener('click', () => { // Adiciona evento de click ao botão...
    let song = document.querySelector('#input').value; // Pega o valor do input...

    if (song !== '') { // Verifica se esse valor é diferente de vazio...
        let songArray = song.split(''); // Pega o valor e transforma em um array...
        handlePlayComposition(songArray); // Passa o array para a função de playComposition...
    }
});