/*
|--------------------------------------------------------------------------
| FUNCTIONS
|--------------------------------------------------------------------------
*/

// Lida com tocar o som da tecla...
function playSound(sound) {
    let audioElement = document.querySelector(`#s_${sound}`); // Pega o valor do id...
    let keyElement = document.querySelector(`div[data-key="${sound}"]`); // Pega o valor do data-key...

    if (audioElement) { // Verifica a variável que recebeu o valor do id...
        audioElement.currentTime = 0; // Seta o time para zero...
        audioElement.play(); // chama a função de tocar...
    }

    if (keyElement) { //Verifica a variável que recebeu o valor do data-key...
        keyElement.classList.add('active'); // Adiciona a class active...

        setTimeout(() => { // Função de tempo...
            keyElement.classList.remove('active'); // Remove o active...
        }, 300); // Após 300 milissegundos...
    }
}

// Lida com tocar do input...
function playComposition(songArray) {
    let wait = 0;

    for (let songItem of songArray) { // Percorre o array...
        setTimeout(() => { // Função de tempo...
            playSound(`key${songItem}`); // Chama a função para tocar o som...
        }, wait); // Após o valor dessa variável ele roda a função setTimeout...

        wait += 250; // A cada vez que o loop roda, incrementa a variável de tempo do setTimeout...
    }
}