// EVENTS...

document.body.addEventListener('keyup', (event) => { // Adiciona evento de soltar a tecla ao body (tela toda)...
    playSound(event.code.toLowerCase()); // Chama a função e passa o parâmetro do código da tecla transformando tudo em caixa baixa...
});

document.querySelector('.drums__composer button').addEventListener('click', () => { // Adiciona evento de click ao botão...
    let song = document.querySelector('#input').value; // Pega o valor do input...

    if (song !== '') { // Verifica se esse valor é diferente de vazio...
        let songArray = song.split(''); // Pega o valor e transforma em um array...
        playComposition(songArray); // Passa o array para a função de playComposition...
    }
});

// FUNCTIONS...

function playSound(sound) { // Lida com tocar o som da tecla...
    let audioElement = document.querySelector(`#s_${sound}`); // Pega o valor do id...
    let keyElement = document.querySelector(`div[data-key="${sound}"]`); // Pega o valor do data-key...

    if (audioElement) { // Verifica a variável que recebeu o valor do id...
        audioElement.currentTime = 0; // Seta o time para zero...
        audioElement.play(); // chama a função de tocar...
    }

    if (keyElement) { //Verifica a variável que recebeu o valor do data-key...
        keyElement.classList.add('active'); // Adiciona a class active...

        setTimeout(() => { // Função de tempo...
            keyElement.classList.remove('active'); // Remove o active...
        }, 300); // Após 300 milissegundos...
    }
}

function playComposition(songArray) { // Lida com tocar do input...
    let wait = 0;

    for (let songItem of songArray) { // Percorre o array...
        setTimeout(() => { // Função de tempo...
            playSound(`key${songItem}`); // Chama a função para tocar o som...
        }, wait); // Após o valor dessa variável ele roda a função setTimeout...

        wait += 250; // A cada vez que o loop roda, incrementa a variável de tempo do setTimeout...
    }
}